feat(productivity-suite): Add query param for piercing enabled
cloudflare/workers-web-experiments pull request #59
Opened 2022-11-08 22:30 UTC by jculvey

2022-11-08 22:34 UTC, IgorMinar approved these changes
LGTM! Thank you

2022-11-09 11:19 UTC, petebacondarwin requested changes

2022-11-09 11:46 UTC, dario-piotrowicz commented on productivity-suite/app/legacy-app/index.html
> +      const initialPiercingEnabledValue = !cookieMatch ? searchParams.get("piercingEnabled") === 'true' : cookieMatch[1] === 'true' ? true : false;
yeah I think they are available:
https://caniuse.com/?search=nullish
https://caniuse.com/mdn-javascript_operators_optional_chaining

2022-11-09 11:48 UTC, dario-piotrowicz commented on productivity-suite/app/legacy-app/index.html
> +      const initialPiercingEnabledValue = !cookieMatch ? searchParams.get("piercingEnabled") === 'true' : cookieMatch[1] === 'true' ? true : false;
ah yeah you version's much better 🙂

2022-11-09 19:08 UTC, petebacondarwin requested changes
As discussed in the meeting. The Gateway worker should be responsible for updating the cookie based on the query param, and then the client-side app can just read the cookie.

2022-11-09 20:39 UTC, dario-piotrowicz commented
> ~As discussed in the meeting. The Gateway worker should be responsible for updating the cookie based on the query param, and then the client-side app can just read the cookie.~
> 
> Oh actually, I think that we don't want the cookie to change just because the search params overrides it... So this is probably fine, once we have fixed up the login in the client-side, right?

I had this conversation with James earlier, I think we do need the cookie to work because we want to have the checkbox checked on the browser, so we either override the cookie or find a different way to check the checkbox

Regarding the login, I thought your PR for it was all ready? is something still missing?

2022-11-10 18:32 UTC, closed without merging